version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: "nginx_like"
    privileged: true
    ports:
    - 80:80
    - 443:443
    volumes:
    - "./server:/srv"
    - "./nginx/conf.d:/etc/nginx/conf.d"
  fpm72:
    image: dockette/php:7.2-fpm
    container_name: "fpm72_like"
    privileged: true
    volumes:
    - "./server:/srv"
    - "./php/999-custom.ini:/etc/php/7.2/fpm/conf.d/999-custom.ini"
  mysql:
    image: "mysql:5.7"
    container_name: "mysql57_like"
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "a754192d654b188f666328f936281689"
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    volumes:
    - "mysql_data_dir:/var/lib/mysql/"
    - "./mysql.conf.d:/etc/mysql/mysql.conf.d"
    # 低版本docker加一个,实现volumes正常
    privileged: true
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin_like"
    ports:
      - 12346:80
    environment:
      PMA_ARBITRARY: 1
  # redis:
  #   image: redis
  #   container_name: "redis_like"
  #   privileged: true
  #   ports:
  #   - 6379:6379
  # redisadmin:
  #   image: erikdubbelboer/phpredisadmin:latest
  #   container_name: "redisadmin_like"
  #   privileged: true
  #   ports:
  #   - 6380:80
  #   environment:
  #     REDIS_1_HOST: "redis"
  #     REDIS_1_NAME: "redis_1"
  #     PHP_CLI_SERVER_WORKERS: 10
# 使用本地路径
volumes:
  mysql_data_dir:
